/** French labels for dictionary keys, so the generated forms read like plain questions. */
export const fieldLabels: Record<string, string> = {
  hero: 'Haut de page (hero)',
  partnersLabel: 'Titre du bandeau partenaires',
  about: 'À propos',
  services: 'Services',
  experience: 'Parcours',
  education: 'Formation',
  research: 'Recherche',
  contact: 'Contact',
  footer: 'Pied de page',
  meta: 'Référencement Google',
  nav: 'Menu',
  marquee: 'Bandeau de mots-clés',
  notFound: 'Page introuvable (404)',
  projects: 'Références',

  title: 'Titre',
  text: 'Texte',
  lead: 'Accroche',
  kicker: 'Sur-titre',
  headline: 'Grand titre',
  name: 'Nom',
  role: 'Fonction',
  intro: 'Introduction',
  badge: 'Pastille de disponibilité',
  cta: 'Bouton principal',
  cv: 'Bouton CV',
  photoAlt: 'Description de la photo (accessibilité)',
  portraitAlt: 'Description du portrait (accessibilité)',
  cardTitle: 'Carte sur la photo — titre',
  cardText: 'Carte sur la photo — texte',
  proof: 'Chiffres clés',
  stats: 'Chiffres clés',
  value: 'Valeur',
  label: 'Libellé',
  yearsValue: 'Années — valeur',
  yearsLabel: 'Années — libellé',
  statement: 'Citation',
  items: 'Éléments',
  icon: 'Pictogramme',
  description: 'Description',
  tags: 'Mots-clés',
  period: 'Période',
  place: 'Lieu / client',
  organization: 'Organisation',
  location: 'Lieu',
  highlights: 'Points forts',
  publicationsTitle: 'Titre — publications',
  publications: 'Publications',
  year: 'Année',
  venue: 'Revue / conférence',
  href: 'Lien',
  distinctionsTitle: 'Titre — distinctions',
  distinctions: 'Distinctions',
  issuer: 'Décerné par',
  membershipsTitle: 'Titre — affiliations',
  memberships: 'Affiliations',
  readLabel: 'Libellé du lien « lire »',
  degrees: 'Diplômes',
  school: 'Établissement',
  languagesTitle: 'Titre — langues',
  languages: 'Langues',
  level: 'Niveau',
  softwareTitle: 'Titre — logiciels',
  software: 'Logiciels',
  formTitle: 'Titre du formulaire',
  formText: 'Texte du formulaire',
  namePlaceholder: 'Exemple affiché — nom',
  email: 'Champ e-mail',
  emailPlaceholder: 'Exemple affiché — e-mail',
  subject: 'Champ sujet',
  subjects: 'Sujets proposés',
  message: 'Champ message',
  messagePlaceholder: 'Exemple affiché — message',
  submit: 'Bouton d’envoi',
  sending: 'Texte pendant l’envoi',
  success: 'Message de succès',
  error: 'Message d’erreur',
  rights: 'Mention de droits',
  backToTop: 'Retour en haut',
  back: 'Bouton retour',
  keywords: 'Mots-clés Google',
  openMenu: 'Ouvrir le menu',
  closeMenu: 'Fermer le menu',
  toggleTheme: 'Changer de thème',
  language: 'Langue',
  skip: 'Lien d’évitement',
  menuContactTitle: 'Menu mobile — titre',
  menuContactText: 'Menu mobile — texte',
  follow: 'Libellé réseaux sociaux',
  id: 'Identifiant',
  linkLabel: 'Libellé du lien',
};

/** Keys whose values are long paragraphs. */
export const longTextKeys = new Set(['text', 'intro', 'description', 'statement', 'lead', 'formText', 'menuContactText', 'highlights']);

export function labelFor(key: string) {
  return fieldLabels[key] ?? key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase());
}
